# Generated by Django 4.2 on 2023-05-07 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_order_details_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
    ]
